version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mongo_database
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  flask:
    build:
      context: ./app
    container_name: flask
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb